name: "Create Release PR with Release Please"

on:
  workflow_dispatch:

permissions:
    contents: write
    issues: write
    deployments: write
    id-token: write # to enable use of OIDC for npm provenance and trusted publishing

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: 'Setup Environment'
        id: setup
        uses: ionic-team/capacitor-actions/setup-tools@0593e5113cff6305d18e218c9d6768fd010406b4
        with:
          working-directory: ./packages/capacitor-plugin
          gh-token: ${{ github.token }}
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ github.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ github.ref_name }}
