name: "Release Plugin"

on:
  workflow_dispatch:

permissions:
    contents: write
    issues: write
    deployments: write
    id-token: write # to enable use of OIDC for npm provenance and trusted publishing

jobs:
  setup:
    uses: ./.github/workflows/reusable_setup.yml
    secrets:
      THE_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  release-please:
    runs-on: ubuntu-latest
    needs: 'setup'
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ github.ref_name }}
