name: "Build Plugin"

on:
  workflow_call:
    secrets:
      THE_GH_RELEASE_TOKEN:
        required: false

jobs:
  build:
    runs-on: "ubuntu-latest"
    timeout-minutes: 30
    steps:
      - name: 'Setup Environment'
        id: setup
        uses: ionic-team/capacitor-actions/setup-tools@0593e5113cff6305d18e218c9d6768fd010406b4
        with:
          working-directory: ./packages/capacitor-plugin
          gh-token: ${{ github.token }}

      - name: "Copy README.md in root"
        working-directory: ./packages/capacitor-plugin
        run: cp README.md README.md.original

      - name: "Build Packages"
        working-directory: ./packages/capacitor-plugin
        run: npm run build

      - name: "Check README.md changes"
        working-directory: ./packages/capacitor-plugin
        run: |
          if ! cmp --silent README.md README.md.original; then
            echo "Detected README.md changes; Do 'npm run build' to update the docs."
            exit 1
          fi
