name: "Lint Plugin"

on: 
  workflow_call:
    secrets:
      THE_GH_RELEASE_TOKEN:
        required: false

jobs:
  lint:
    runs-on: 'macos-15'
    timeout-minutes: 30
    steps:
      - name: 'Setup Environment'
        id: setup
        uses: ionic-team/capacitor-actions/setup-tools@0593e5113cff6305d18e218c9d6768fd010406b4
        with:
          working-directory: ./packages/capacitor-plugin
          gh-token: ${{ github.token }}

      - name: 'Lint Packages'
        working-directory: ./packages/capacitor-plugin
        run: npm run lint